name: Ellirion-BuildFramework
main: com.ellirion.buildframework.BuildFramework
version: 0.0.1
description: Ellirion-BuildFramework
authors: [OldaranT, Chris Coerdes, Nick Kronenberg, Joris Klein Tijssink]
commands:
  Test:
    description: test
    usage: /Test
  Validate:
    description: Validates the terrain for terrain smoothing.
    usage: /Validate


