name: Ellirion-BuildFramework
main: com.ellirion.buildframework.BuildFramework
version: 0.0.1
description: Ellirion-BuildFramework
authors: [OldaranT, Chris Coerdes, Nick Kronenberg, Joris Klein Tijssink, Richard de Vries]
commands:
  CorrectTerain:
    description: Smooths the terain.
    usage: /CorrectTerain, /cor
    aliases: [cor]
  Validate:
    description: Validates the terrain for terrain smoothing.
    usage: /Validate, /va
    aliases: [va]
  CreateTemplate:
    description: create a template of the selected area
    usage: /CreateTemplate, /ct
    aliases: [ct]
  PutTemplate:
    description: Places the current selected tempalte.
    usage: /PutTemplate, /pt
    aliases: [pt]
  ExportTemplate:
    description: Export current selected template to a json file.
    usage: /ExportTemplate, /et
    aliases: [et]
  ImportTemplate:
    description: Import a template from a json file
    usage: /ImportTemplate, /it
    aliases: [it]

