name: Ellirion-BuildFramework
main: com.ellirion.buildframework.BuildFramework
version: 0.0.1
description: Ellirion-BuildFramework
authors: [OldaranT, Chris Coerdes, Nick Kronenberg, Joris Klein Tijssink]
commands:
  CreateTemplate:
    description: create a template of the selected area
    usage: /CreateTemplate, /ct
    aliases: [ct]
  PutTemplate:
    description: Places the current selected tempalte.
    usage: /PutTemplate, /pt
    aliases: [pt]
  Chest:
    description: make chest
    usage: /chest
